In [ ]:
import timeit
list_creation = "[i for i in range(1000)]"
list_time = timeit.timeit(stmt=list_creation, number=10000)
print(list_time)

In [ ]:
import timeit
set_creation = "(i for i in range(1000))"
set_time = timeit.timeit(stmt=set_creation, number=10000)
print(set_time)

In [ ]:
dict_creation = "{i: i**2 for i in range(1000)}"
dict_time = timeit.timeit(stmt=dict_creation, number=10000)
print(f"Time to create dictionary: {dict_time} seconds")

Exception Handling


In [ ]:
while True:
  try:
    x = int(input("please enter a number: "))
    break
  except ValueError:
    print("This is not a valid number")

In [ ]:
try:
  numerator = 10
  denominator = 0
  result = numerator / denominator
  print(result)
except ZeroDivisionError:
  print("Denominator cannot be zero")

Functions

In [6]:
x = 3.4
remainder = x % 1
if remainder < 0.5:
  print("Number is rounded down")
  x = x - remainder
else:
  print("Number is rounded up")
  x  = x + (1- remainder)
print("Final answer is", x)


Number is rounded down
Final answer is 3.0


In [7]:
def printNum(num):
  print("My favourite number is ", num)

printNum(5)
printNum(4)
printNum(8)

My favourite number is  5
My favourite number is  4
My favourite number is  8


In [10]:
def roundingFn(x):
    remainder = x % 1
    if remainder < 0.5:
        print("Number is rounded down")
        x = x - remainder
    else:
        print("Number is rounded up")
        x = x + (1 - remainder)
    return x


roundedValue = roundingFn(5.6)
print(roundedValue)


Number is rounded up
6.0


In [4]:

def printName():
  x = 10
  print("Hello world")
  print("Still in function")
  if x > 9:
    print("In if")
  print("out of if and out  of function")


printName()
print("out of function")



Hello world
Still in function
In if
out of if and out  of function
out of function


In [38]:
#line = "Hello"
text_file2 = open("write_it.txt","r+",encoding="utf-8")
print(text_file2.write("line 4"))

print(text_file2.tell())
text_file2.seek(0)
print(text_file2.read())
text_file.close()
text_file.close()




6
6
line 4


In [16]:
text_file = open("Users/sheetal/Downloads/read_it.txt","r")
print(text_file.readlines())

FileNotFoundError: [Errno 2] No such file or directory: 'Users/sheetal/Downloads/read_it.txt'

Numpy


In [48]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6]]) #create a rank 1 array

print(type(array1))

print(array1.shape)

print(array1[0,0])
print(array1)

<class 'numpy.ndarray'>
(2, 3)
1
[[1 2 3]
 [4 5 6]]


In [50]:
arrayOfZeros = np.zeros((2,2))
print(arrayOfZeros)
print(arrayOfZeros.shape)

[[1. 1.]
 [1. 1.]]
(2, 2)


In [51]:
arrayOfones = np.ones((1,2))
print(arrayOfones)
print(arrayOfones.shape)

[[1. 1.]]
(1, 2)


In [53]:
array2 = np.full((2,2),7)
print(array2)


[[7 7]
 [7 7]]


In [55]:
identityArray = np.eye(2)
print(identityArray)

[[1. 0.]
 [0. 1.]]


In [58]:
randomArray = np.random.random((2,2))
print(randomArray)
randomArray

[[0.46270096 0.30892855]
 [0.60265917 0.20073439]]


array([[0.46270096, 0.30892855],
       [0.60265917, 0.20073439]])

In [61]:
x = np.array([[1,2],[3,4]] ,dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

print(x + y)
print(np.add(x,y))

#subtract
#multiply
#divide
#sqrt
np.sqrt(x)
x.dot(y)
np.dot(x,y)


np.sum(x, axis =0)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
